### ISSUE TITLE
Allow table functions to access dashboard variables

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1143]
I with to be able to produce a link() that passes on the values of the dashboard variables

**Comment by stroomdev10** [comment]
It would be useful to have a shorthand to pass *all* the dashboard variable to the child dashboard.

Given this, it would also good to be able to override values that are passed using the above

**Comment by stroomdev66** [comment]
maybe params should be got using a function rather than `${param}` syntax. That way we could have `params()` for getting the whole params string and perhaps `param('paramName')` for getting a single param value. This was there wouldn't be confusion between params and data fields.
We could just make it a rule that the last value assigned to a param in a list is the overriding one
