### ISSUE TITLE
At any time it should be possible for a child items permissions to be set to inherit or copy from the parent folder.

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#134]

**Comment by jc064522** [comment]
I have a few understanding/clarification questions:

1. Why wouldn't you want to update the parent's permissions and cascade all? Perhaps because the child item might have siblings which shouldn't have the parent's permissions?

2. Would a user want the same cascade options for copying from a part as they would have when setting permissions normally?

3. I'd assume a user would expect to see this option on the 'Set folder permissions' dialog. Is that right?

**Comment by jc064522** [comment]
PR: https://github.com/gchq/stroom/pull/734
