### ISSUE TITLE
Find a way to auto add an API key to proxy in the stack

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#1465]

**Comment by at055612** [comment]
In summary proxy needs to make a rest call to stroom to check the receive status of feeds.  To make this call it needs an API key.  So that the stack can work straight out of the box, proxy will need to come with baked in test token.  This token would have to be pre-created using a client aud and a public key that would have to be baked into stroom so it can verify the token from proxy.

It probably makes sense for stroom to have a config section for set the details for the test token infrastructure, client id, aud, etc. that can then be disabled for production hardening.

For production hardening the generation of the public key and client id/aud will need to be auto-generated but triggered from running the stroom jar with a command argument.  It would then store the various bits in the DB.

**Comment by at055612** [comment]
Also, `stroom.security.impl.OpenIdClientDetails` needs renaming to OpenIdClientDetailsFactory or similar as it looks too much like a pojo with the current name.

**Comment by at055612** [comment]
Following a conversation:
In stroom repo create a main() method to generate a public key and an API key from a noddy client id and client secret.  Main method is expected to be run by hand by a dev in the IDE.  Maybe create a run config for it so it is easier to find.
Add the public key, client id and client secret to prod.yml in a new block called `testOnlySeedOpenIdDetails` or similar.
Add the token to proxy-prod.yml in its usual place.
Change the OpenIdClientIdFactoryImpl to first read the DB, if it is empty and `testOnlySeedOpenIdDetails` is populated, persist those to the DB, else generate some proper ones.
Add a dropwiz command to allow the regeneration of the open id secrets that we gen new details and store them to the DB.  Maybe call the command `harden` to allow for other hardening processes later.

Heavily document `testOnlySeedOpenIdDetails` so it is clear that the values are only for use in a test system.

Need to also pre-create a proxy user that the proxy token can be associated with.
