### ISSUE TITLE
Properties UI Inconsistencies for Default and Effective values

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1508]
Whilst some of the properties fields (e.g stroom.authentication.oauth2.accessCodeCache.expireAfterAccess) show both a Default and Effective value, others (e.g. stroom.annotation.db.connectionPool.maxLifetime show both fields as blank although the Description field does show the default within its text.  Others still (e.g. stroom.authentication.oauth2.accessCodeCache.expireAfterWrite) don't even have a default in the Description field.

I'd expect all values to have an Effective value displayed, even if the value is <not specified>.

As a minor observation, I found I was unable to copy the above field names from my browser, making reporting a bit error prone - is this intentional or easily changeable?

**Comment by at055612** [comment]
I have update the descriptions for the Cache properties.

For the connectionPool props, this is tricky.  Defaults are quoted in the description because if stroom doesn't set a value on the hikari connection pool then it will use its defaults.  We could copy their defaults to make ours but that is not ideal if hikari is updated and its defaults change.  I could make it more clear in the documentation that if no value is set then the Hikari default will be used. Also quoting their defaults in the description may not be wise if we can just refer to their documentation.

**Comment by at055612** [comment]
I'm not really sure what you mean by this?

> I'd expect all values to have an Effective value displayed, even if the value is .

The effective value field is always greyed out as it is never writable.  A lot of props will have no default and thus no effective value (i.e. an empty text box).

**Comment by at055612** [comment]
I have now changed the connection pool properties so that they have proper default values set.
