### ISSUE TITLE
Text Pane on dashboard is not displaying a full record when line /col values are specified

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1678]
I have processed some XML fragments and captured the stroom:source() in the cooked event.

When displaying the source Stream in a data popup, the relevant record is highlighted, very nice.

<img width="804" alt="Screen Shot 2020-06-19 at 11 27 59" src="https://user-images.githubusercontent.com/28703366/85123317-f4dbd780-b21f-11ea-9cf2-a1a61c00426d.png">

However when using the Text pane on a dashboard, the record is being trimmed.  The source for this is showing lineFrom=1, lineTo=30

<img width="1133" alt="Screen Shot 2020-06-19 at 10 16 36" src="https://user-images.githubusercontent.com/28703366/85116950-fdc7ab80-b215-11ea-97c3-35b95584e12b.png">

The pane is only displaying lines 1->29

**Comment by at055612** [comment]
See also #1679

**Comment by at055612** [comment]
This issue has morphed into addressing the issues around 'paging' over the data in the DataPresenter.  Currently paging is done by paging a set number of lines.  This does not work if the data is one large single line and can break the UI.  The new approach is to page in chunks of characters and to allow selection of the displayed range in terms of char offsets, line:col positions and numbers of chars.

It has also raised issues around the display of the data in a formatted from.  Currently single line XML will be auto-formatted for display into multi-line indented xml.  While better to look at, this will cause confusion when selecting a range of data to view as the user sees multi-line data when the actual data is single line.  The data may be a multi-Gb stream so formatting all of it to select a range is not viable.

To address the issues it is proposed to change the existing data viewer so that it only shows a formatted preview of the data and cannot page around it.  In order to see the data in a full pageable raw form, a new raw (raw as in what is stored and not raw as in raw/cooked) data viewer top level tab will be opened.  This ties in with changes to the tabs shown in the data viewer pane as set out in #1777. 

## Existing Data Viewer (data streams)
### Meta tab (formally stream tooltip, always visible)
* One set per stream.
* All stream types have a Meta tab
* Shows what was in the stream tooltip
* Works the same way as the Data Preview Tab
### Data Preview tab (always visible)
* 1-* parts/segments
* Displays ONLY the 1st n chars of the 1st part/segment, or the 1st n errors.
* Data is formatted as if it is XML
* No line numbers in Ace editor (as the line numbers may differ from the raw data)
* No paging controls at all, what you see (and what you can scroll over in Ace) is all you get.
* A button to open in stepper
* A button to open this data in new top level RawDataViewer tab
* Some indication if there is more data available.
### Headers tab (formally meta, only visible if headers are present)
* 1-* sets (1 per part)
* Show parts paging controls
### Context Preview tab (only visible if context data is present)
* 1-* parts
* Works the same as the Data Preview Tab
### Error tab (only visible for an error stream)
* 0-* errors per stream
* Shows table of error records grouped by type

## New Raw Data/Context Viewer tab
* Shows data in raw unformatted form.
* Show line numbers in Ace editor
* Shows stream ID in tab text
* Show paging controls for part/rec and char range
* Link to open AT's new Source Location selection screen
* A button to open in stepper
