### ISSUE TITLE
Explorer tree searching by UUID doesn't work

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1694]
searching by using `#nnn` isn't working

Also shouldn't this be  this be `uuid:nnn`

**Comment by at055612** [comment]
This has been broken by the introduction of the field qualifiers.  The explore QF defines DocRef::getName as the default field and then works off string predicates rather than DocRef predicates so will never look for a UUID.

Probably need to create a common FilterFieldMappers<DocRef> the defines name as the default with uuid and type as qualified fields.  This common mappers object can then be used anywhere we want to filter on just docrefs.

Need to check it works in suggesters as well as QFs.

**Comment by at055612** [comment]
See comments in #1810
