### ISSUE TITLE
Mismatch document count. Index says 4068 DB says 0

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1795]
```
ERROR 2020-08-17T12:51:22.898Z Data Processor# #6 - Data Processor s.i.i.IndexShardWriterImpl     Mismatch document count. Index says 4068 DB says 0 
```
Saw this having done the following:
Empty DB
Ran SetupSampleData
Started the app
Pipeline process kicked off automatically

Seen in beta.45

**Comment by gcdev373** [comment]
This can be caused by failing to delete the shards within the index volumes used by Stroom when the database is emptied.

Retested with `v7.0-beta.67` and could not reproduce when the directories that contain index volumes are removed prior to following the steps described.

Closing, appears to be expected behaviour.
