### ISSUE TITLE
Neither Tools/Users nor Tools/API Keys brings up expected tab

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1928]
New docker stack downloaded from https://github.com/gchq/stroom-resources/releases/download/stroom-stacks-v7.0-beta.68-2/get_stroom.sh and run on a VMWare VM.

Start stroom and neither of the mentioned Tools works.  No unexpected log entries generated.  This happens for at least two different (physical) users.

**Comment by at055612** [comment]
This is working fine.  The issue was caused by the browser auto-completing the url to `localhost/stroom` rather then using `localhost`.  

There is an argument that the nginx config should be changed so that /stroom is denied to prevent this sort of confusion for other migrating from 6 to 7.  Maybe adding a deny rule for `/stroom($|/$/ui)` would achieve this without breaking things for the servlets under /stroom
