### ISSUE TITLE
Allow recursive delete of a folder

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#20]
Currently deleting a folder that contains entities fails with a FK violation.  Need to give the user the option to delete all the contents as well (including any sub folders) or cancel.

**Comment by jc064522** [comment]
We can delete a folder with items in it already. 

We would have trouble deleting a folder if it contained an index, because the shards would need deleting. Do we want entity-specific strategies for deletion? Is that what this defect refers to?

Needs discussion with @stroomdev66, @stroomdev10, and @at055612.
