### ISSUE TITLE
Allow sorting of tabular data displays

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#216]
In various tabular displays - eg the Data tab of a Event Feed, the Shards tab of an Index, allow columns to be sorted based on current locale sort posture given the column's data format. This is already achieved in tabular displays such as the System's or a Pipelines Active Tasks displays.

**Comment by stroomdev66** [comment]
Sorry but I'm not totally sure I understand this issue. Could you provide some examples?

**Comment by burnalting** [comment]
Currently a number of display tables, for example, the System's 'Active Tasks' table can sort it's columns as per
![image](https://cloud.githubusercontent.com/assets/10084635/25297738/1f8205a2-2733-11e7-9e52-9b42948e5a57.png)

This feature request is to allow other tabular displays to do the same. For example
- an Index's 'Shards' table
![image](https://cloud.githubusercontent.com/assets/10084635/25297795/7e5a0b2e-2733-11e7-9282-570b75558693.png)

- a Feed's 'Data' table

![image](https://cloud.githubusercontent.com/assets/10084635/25297824/ada37dac-2733-11e7-8e3a-fa23a682cece.png)

**Comment by jc064522** [comment]
@burnalting  @stroomdev66: I've closed this. We now have individual issues for adding sorting to tables. I don't think these issues cover all tables in the application, but they're @stroomdev10's top 5.  These other issues are gh-725, gh-726, gh-727, gh-728, gh-279. If they don't cover everything please feel free to create new ones for each table.

I'm also closing this issue because it covers too much to be actionable, so it will just hang around being hard to prioritise and close.
