### ISSUE TITLE
v6-v7 migration issue

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2183]
[210421-mig.txt](https://github.com/gchq/stroom/files/6348750/210421-mig.txt)

**Comment by at055612** [comment]
This is an issue where we have a prop that contains a delimiter set of things.  In v6 the code that consumed the prop would be responsible for splitting the string.  In v7 the prop has been typed to be a `List<String>` so it is trying to deserialise the delimited string into the typed object and failing because our simple serialisation requires the delimiter in use to be at the start of the string, i.e. `,one,two,three`.

The prop migration class needs some additional code for props that are migrating from a simple str that contains delimited values to a List<String> to add the required delimiter prefix.

**Comment by at055612** [comment]
Properties known to have commas in their values are:
stroom.search.storeSize - String in v7
stroom.theme.labelColours - String in v7 
stroom.maintenance.message - String in v7 (not a collection)
stroom.splash.body - String in v7 (not a collection)
stroom.activity.editorBody - String in v7 (not a collection)
stroom.anotation.statusValues - List<String> in v7
stroom.anotation.standardComments List<String> in v7
stroom.query.infoPopup.validationregex - String in v7 (not a collection)
stroom.internalstatistics.*.docRefs - List<DocRef> in v7

**Comment by at055612** [comment]
Fixed in b.108
