### ISSUE TITLE
LMDB ref load appears to lockup if when loading missing reference data stream

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2666]
I have a Reference stream that is missing the file on the file system, but the meta exists.

When the refloader tries to load the data it appears to get stuck and never returns back to the translation.

[RefLoad_20211220.txt](https://github.com/gchq/stroom/files/7746207/RefLoad_20211220.txt)

**Comment by at055612** [comment]
Changed it to handle the IO error and log a FATAL.  The problem was it had not written the processing info record for the stream at the point the stream was read.  I now writes the record sooner so it can record the failure properly.

![image](https://user-images.githubusercontent.com/22818309/146824932-66b35445-3601-4e24-9de0-054335a2d943.png)

**Comment by at055612** [comment]
Fixed in >b.169
