### ISSUE TITLE
Mismatch document count ERROR thrown a lot

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#293]
server.IndexShrdWriterImpl (IndexShardWriterImpl.java:236) - Mismatch document count.  Index says 123456789 DB says 123456788

Consistently the DB count is -1 from the Index.

**Comment by stroomdev10** [comment]
Actually some are +/- 5

**Comment by stroomdev66** [comment]
The document count could still be inaccurate if a thread is still adding a document while the index shard is being closed and we get there after the document has been added but before the 'actualDocumentCount' variable has been incremented.

Further more the close method is called when the writer cache is asked to dispose of an index shard. If this happens because a thread has failed to add a document (this might be because the count has been exceeded) and has then asked the cache to dispose of this shard, we might still have many threads that are in the process of trying to add documents at the same time as we are closing the shard. This could lead to this index shard having a document count that is less than the maximum document count even though the limit has been met by some shards.
