### ISSUE TITLE
Data Volumes , cannot view value of 19.1T , shows as 19T

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3305]
Have set a volume limit at 19.1T, renders on screen as 19T, value is correctly set in DB

Tried 9.1T, rendered OK

**Comment by at055612** [comment]
The code only includes the decimal place if the value is <10 which is why the decimal place is being visually 'lost'.
While we could change this to show 1dp if the value is <100 or round to 3 significant figures the fundamental problem is that we should be storing what the user entered and not the bytes equivalent which is a lossy conversion given you often end up with fraction bytes, which we cannot store.  This requires a db migration to fix so should be addressed in 7.2+

**Comment by at055612** [comment]
Agreed to change the display of only the idx/fs volume limit value to show 3 significant figures, pending a longer term fix to store the user input as is.

**Comment by at055612** [comment]
Raised #3312 to fix it properly

**Comment by at055612** [comment]
Tactically fixed in >7.0.24
