### ISSUE TITLE
Started an upgraded 7.2 (from 7.0) getting job tracker error for some jobs on master

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3343]
```ERROR - [Stroom Job - ScheduledExecutor] stroom.job.impl.ScehduledTaskExecutor - No job node tracker found for: Alert Rule Refresh```

Also occurring for` Aggregate Alert Rule Executor `and` Elastic Index Retention`

**Comment by stroomdev66** [comment]
For some reason one of the nodes failed to create job_node records in the database.  The `JobBootstrap`  `startup()` method should have created the job_node entries for the new jobs described in this issue but seems to have failed to do so. This failed on the first node that was started when no other nodes were running so shouldn't have been due to cluster lock contention.

At this time it is not clear as to why this problem occurred and the offending node did manage to create the missing DB records on restart. One aspect that appeared strange is that not all of the records had been created as `PROCESSING_USER` as expected.

**Comment by stroomdev66** [comment]
Closing for now
