### ISSUE TITLE
Dashboard Query Builder is slow to pick fields if an index has > 1000 fields

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3723]

**Comment by at055612** [comment]
We need to consider implementing virtual scrolling to reduce the number of dom elements, e.g. https://dev.to/adamklein/build-your-own-virtual-scroll-part-i-11ib.

Also the field picker control needs to change to use the back-end quick filter code to be consistent with the other filter boxes in stroom.  Also, the term value suggest drop down needs to change to use the SelectionPopup instead of SuggestBox.
