### ISSUE TITLE
Querying an Index for fieldX='blah' or empty doesn't work.

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#486]
I'm attempting to query for events where fieldX is a value or empty.

My query is Time>day() and (fieldX=‘blah’ or NOT(fieldX=*))

This returns events with fieldX=blah only

if i comment out fieldx=blah, I get correct not(fieldX=*) events (empty fieldX)

if i comment out not(fieldX=*) I get correct fieldlX=blah events

**Comment by stroomdev66** [comment]
This is down to the way Lucene works. NOT is actually to be treated as (-) in which case it removes results rather than negating single terms. This way this works is made a little more confusing due to the expression tree that we present but either way NOT must be treated more like a filter that removes results rather than something that finds matching data.

In the example above:
```
AND
   Time > day()
   NOT
      fieldX=*
```
will work because Lucene will find all data for today and then remove all items that have something defined for fieldX.

```
AND
   Time > day()
   OR
      fieldX='blah'
      NOT
         fieldX=*
```
will not work as intended as the expression is contradictory `+fieldX:blah -fieldX:*` so you just get results where fieldX is 'blah'

To achieve the desired result you must do the following
```
AND
   OR
      AND
         Time > day()
         fieldX='blah'
      AND
         Time > day()
         NOT
            fieldX=*
```
Obviously this is more complicated but it is the only way you can get Lucene to return the correct results. It means that NOT terms are fairly pointless inside OR.

**Comment by stroomdev10** [comment]
Happy with the explanation
