### ISSUE TITLE
Unable to copy an entity

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#587]
Seen in `v6.0-alpha.6`

Steps to recreate:
1. Right click on an entity in the explorer pane
1. Select copy
1. Select the folder of the original entity
1. Click OK

An Alert will be shown saying:
`Unable to copy 'NAME_OF_ENTITY' org.hibernate.HibernateException: identifer of an instance of stroom.pipeline.shared.XSLT was altered from 2 to -1`

Stroom5 used to give you the option to change the name in a copy dialog, thus allowing you to copy into the same folder.  It should either cleanly tell you that you can't copy into the same folder, give you the option of choosing a new name, or do what windows does and auto rename the copy if it is the same folder.

**Comment by at055612** [comment]
It looks like trying to copy to any folder (duplicate or not) causes this error.  Therefore currently unable to copy an XSLT entity.

**Comment by GCHQ-11** [comment]
It seems as though within the copy function, we are modifying an entity that is still 'attached' to hibernate. So I have added the ability to 'detach' from hibernate before making modifications and attempting to save. This seems to do the trick. Wherever you put the copy, it will put 'Copy of' in front of the existing name, so that seem fine.
