### ISSUE TITLE
Not allowed to use NOT to filter on Status

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom#681]
Filtering on status and unable to use NOT Status==Deleted. A dialog is displayed with an explanation that we didn't find elucidating.

**Comment by GCHQ-11** [comment]
The use of expression trees for stream selection is not yet powerful enough to allow the user to specify any old shape of expression.
There are various limitations caused by the underlying storage of that meta data and the way we currently have to query it.
The error seems clear enough, the problem I found is that the processing filter UI doesn't give you the same dialog, but that error is instead dumped to the console and the pipeline fails to process. This is completely invisible to the UI.
