### ISSUE TITLE
Reference Data caching issues

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#697]
Stroom appears to be caching reference data such that lookups are utilising reference feeds that have been superseded in the stream store and thus failing to find keys that are expected to be found.

**Comment by stroomdev66** [comment]
Fix for reference data sometimes failing to find the appropriate effective stream due to the incorrect use of the effective stream cache. It was incorrectly configured to use a time to idle (TTI) expiry rather than a time to live (TTL) expiry meaning that heavy use of the cache would prevent the cached effective streams being refreshed.
