### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#876]
The reset password page button ought to have a button just titled 'Send' or 'Send Email'

There is no button to get back to the login page

You should see a page that says email is not configured rather than letting the user try and send an email before finding that out.

You should see an error page if anything goes wrong when trying to send the email including not having email configured or misconfigured.

If an email is sent successfully then you should get a message saying so and then be redirected back to the login page.

**Comment by jc064522** [comment]
On the main reset page:
* changed the copy on the button
* added a button to go back to the login page

There is already a confirmation page but I added a button to go back to the login page. There's not a great deal of point to this button -- if someone has forgotten their login and needs a reset email then the email will have a link to the login page. However it is nice to have a connection back to a main screen. No one wants to see a page in the app that's orphaned.

**Comment by jc064522** [comment]
If email reset is enabled then the link will be displayed. If it's not enabled then it won't be.

**Comment by jc064522** [comment]
There is another bug though: if the user doesn't exist then there is no error message.

**Comment by jc064522** [comment]
There's no longer a 500 if the reset email doesn't exist. There's no explicit error message to this effect either -- it always shows the same confirmation page. But I've changed the copy to say 'if this account exists'. Otherwise it would provide an easy way for a user to look for registered accounts. This is a superficial diversion though, because a user could always check the network logs and see the 404.

Is it worth changing the service layer to not return 404s for a user search?
