### ISSUE TITLE
Unable to copy feeds in UI

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#894]
Commit: 17bb943 on `6.0` branch
In the UI it is not possible to copy feeds, either to the same folder or a different one.  Can copy xslt/pipe/dash ok.
e.g tried copying one of the `internal log` feeds.

**Comment by stroomdev66** [comment]
It is by design that feeds are not copyable because:
* The code to copy them would need to account for their names remaining unique.
* The code to copy them would need to make copies that adhere to the feed naming convention which is much stricter than for other entities.
* When batch copying a bunch of content, copying feeds makes little sense as references to feeds are by name and not by DocRef so feed copies would not end up being repointed to by any of the other copied content.
* Feeds are being killed off eventually in favour of tagged data.

For the time being the UI will now show an error if a user attempts to copy a feed. It has been suggested that the UI shouldn't show the copy menu item for feeds but it is hard to determine whether it should be visible based on the explorer selection. If only a single item is selected then it would be possible but for multiple items it becomes very difficult to ascertain whether or not only folders would be copied. If might also be confusing to users if the menu item appeared for some things and not others so an error message is probably best for now.
